package klase;

public enum TipManifestacije {
	KONCERT,
	FESTIVAL,
	POZORISNA_PREDSTAVA,
	BIOSKOPSKA_PROJEKCIJA,
	SPORTSKA_NADMETANJA,
	PLESNI_NASTUP,
	STANDUP_NASTUP,
	NASTUP_CIRKUSA,
	SAJAM,
	MUZEJSKO_VECE,
	KNJIZEVNO_VECE,
	DRUGA_KATEGORIJA
}
